data: 
  path: '/graphics/scratch2/datasets/practical_course/MIMeta/data'
  datasets:
    - domain: 'Peripheral Blood Cells'
      task: 'cell class'
    - domain: 'Chest X-Ray'
      task: 'disease class'
seed: 12345
lr: 0.03
optimizer: torch.optim.SGD
epochs: 100
batch_size: 192
input_size: 512
hidden_size: 2048
output_size: 2048
img_size: 224
splits: [0.80.10.1]
domain: 'Peripheral Blood Cells'
task: 'cell class'
transform: SimCLRTransform