data: 
  path: '/graphics/scratch3/students/krauseg/data' #'/graphics/scratch2/datasets/practical_course/MIMeta/data'
  datasets:
    - domain: 'crc'
      task: 'tissue class'
   # - domain: 'organs_coronal'
   #   task: 'organ label'
   # - domain: 'organs_sagittal'
   #   task: 'organ label'
evaluation:
  domain: 'Colorectal Cancer'
  task: 'tissue class' #'organ label'
  modelpath: '/home/franksim/SSL_MIA/trained_models/firstrun/epoch=999-step=8000.ckpt'
lr: 0.03
optimizer: Adam
weight_decay: 0.0000015
epochs: 1000
batch_size: 128
img_size: 224
transform: 'SimCLRTransform'
savedmodel:
  path: 'trained_models'
  name: 'firstrun'
usedMethod: 'BarlowTwins'
pretraining:
  method: 
    name: 'BarlowTwins'
    backbone: 
      name: 'resnet18' #'efficientnet_b2' #'vit_b_16' # 
      pretrained: True
    projection_head:
      input_size: 512
      hidden_size: 2048
      output_size: 2048
finetuning:
  pretrained: True 
  trainall: True
  trainsplit: 1
  lr: 0.0001
  epochs: 1000
  output_size: 11
  name: 'finetuningall'
  modelpath: '/home/franksim/SSL_MIA/trained_models/firstrunfinetuning/epoch=995-step=20916.ckpt'
