data: 
  path: '/graphics/scratch2/datasets/practical_course/MIMeta/data'
  datasets:
    - domain: 'organs_axial'
      task: 'organ label'
    - domain: 'organs_coronal'
      task: 'organ label'
    - domain: 'organs_sagittal'
      task: 'organ label'
seed: 12345
lr: 0.03
optimizer: Adam
weight_decay: 0.0000015
epochs: 1000
batch_size: 256
input_size: 512
hidden_size: 2048
output_size: 2048
img_size: 224
transform: SimCLRTransform
model:
  path: 'trained_models'
  name: 'firstrun'