data: 
  path: '/graphics/scratch2/datasets/practical_course/MIMeta/data'
  datasets:
    - domain: 'crc'
      task: 'tissue class'
evaluation:
  domain: 'Colorectal Cancer'
  task: 'tissue class'
  modelpath: '/graphics/scratch2/datasets/practical_course/MIMeta/trained_models/crc/barlowpretrained/epoch=999-step=84000.ckpt'
lr: 0.03
optimizer: Adam
weight_decay: 0.03
epochs: 1000
batch_size: 64
img_size: 224
transform: 'SimCLRTransform'
savedmodel:
  path: 'trained_models'
  name: 'firstrun'
usedMethod: 'BarlowTwins'
pretraining:
  method: 
    name: 'BarlowTwins'
    backbone: 
      name: 'resnet18'
      pretrained: True
    projection_head:
      input_size: 512
      hidden_size: 2048
      output_size: 2048
finetuning:
  pretrained: True 
  trainall: True
  trainsplit: 1
  lr: 0.03
  epochs: 1000
  output_size: 11
  name: 'finetuningall'
  modelpath: '/home/franksim/SSL_MIA/trained_models/firstrunfinetuning/epoch=995-step=20916.ckpt'