data: 
  path: '/graphics/scratch2/datasets/practical_course/MIMeta/data'
  datasets:
    - domain: 'organs_axial'
      task: 'organ label'
    - domain: 'organs_coronal'
      task: 'organ label'
    - domain: 'organs_sagittal'
      task: 'organ label'
evaluation:
  domain: 'Axial Organ Slices'
  task: 'organ label'
  modelpath: '/home/krauseg/SSL_MIA/trained_models/firstrun/epoch=599-step=4800.ckpt'
lr: 0.03
optimizer: Adam
weight_decay: 0.0000015
epochs: 2000
batch_size: 96
img_size: 224
transform: 'VICRegLTransform'
savedmodel:
  path: 'trained_models'
  name: 'firstrun'
usedMethod: 'VicRegL'
pretraining:
  method: 
    name: 'VicRegL'
    backbone: 
      name: 'resnet18'
      pretrained: True
    projection_head:
      input_size: 512
      hidden_size: 2048
      output_size: 2048
finetuning:
  pretrained: False
  trainsplit: 1
  lr: 0.0001
  epochs: 1000
  output_size: 11
  name: 'finetuningpretrained_1'
  modelpath: '/home/franksim/SSL_MIA/trained_models/firstrunfinetuning/epoch=995-step=20916.ckpt'
